### ISSUE TITLE
Not clear how to install this into a Swift project

### ISSUE THREAD

**Issue by novumcoder** [yohei-yoshihara/Box2DSwift#2]
Could you please provide information on how to install the Box2D port for Swift into an existing Swift project?

Thanks

**Comment by yohei-yoshihara** [comment]
There are two ways to add Box2DSwift to your project: A) framework binary, B) source code.

A) framework binary
Sadly, it seems that there is no easy way to create a framework binary. [This post](http://stackoverflow.com/questions/34643800/how-to-build-a-release-version-of-an-ios-framework-in-xcode) would be helpful.
After creating the framework binary, simply drag and drop it to your project.

B) source code
1) Open your project with Xcode.
2) "File" -> "New" -> "Target", select "Cocoa Touch Framework"
3) Enter "Box2D" as Product Name.
4) Drag and drop 4 folders ("Collision", "Common", "Dynamics", "Rope") under "Box2DSwift/Box2D" folder to Box2D target.
5) Add "Box2D.framework" as "Embedded Binaries".

**Comment by novumcoder** [comment]
Thanks for the info.

I tried option B. Worked fine so far, but still after adding "import Box2D" in my Swift file it still complains it cannot find b2World or b2Vec2 when i try to instantiate it. Point 1 to 5 worked fine. After building the Box2D the Box2D.framework file is added as embedded binary automatically.

What is missing here?

**Comment by yohei-yoshihara** [comment]
I created an app with option B, and uploaded it to github [Box2DSwift_MinimumApp](https://github.com/yohei-yoshihara/Box2DSwift_MinimumApp).

**Comment by novumcoder** [comment]
Oh great thanks a lot
